spring:
  servlet:
    multipart:
      maxFileSize: 1000MB
      maxRequestSize: 2000MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    group:
      "local": "testdb,common"
      "dev": "testdb,common"
      "prod": "proddb,common"

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: error

server:
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie

image:
  dir: C:/Users/spa89/Downloads/develop/springCommuProject/file/image/

video:
  dir: C:/Users/spa89/Downloads/develop/springCommuProject/file/video/

---
spring:
  config:
    activate:
      on-profile: "proddb"
  datasource:
    url: jdbc:mysql://localhost:3306/testDB?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver

---

spring:
  config:
    activate:
      on-profile: "testdb"
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

