spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/community
    username: sa
    password:
    driver-class-name: org.h2.Driver
  servlet:
    multipart:
      maxFileSize: 1000MB
      maxRequestSize: 2000MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
#    default: local
    group:
      "local": "testdb,common"
      "dev": "testdb,common"
      "prod": "proddb,common"
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

cloud:
  aws:
    s3:
      bucket: healthcommunitybucket
    credentials:
      access-key: AKIAVDREP22CSUO6CW4W
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false


logging:
  level:
    org.hibernate.SQL: error
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR

server:
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie

image:
  dir: C:/Users/spa89/Downloads/develop/springCommuProject/file/image/

video:
  dir: C:/Users/spa89/Downloads/develop/springCommuProject/file/video/



---
spring:
  config:
    activate:
      on-profile: "proddb"
  datasource:
    url: jdbc:mysql://localhost:3306/post?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver

image:
  dir: /home/ubuntu/healthCommunity/image/

video:
  dir: /home/ubuntu/healthCommunity/video/

---

spring:
  config:
    activate:
      on-profile: "testdb"
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
image:
  dir: C:/Users/spa89/Downloads/develop/springCommuProject/file/image/

video:
  dir: C:/Users/spa89/Downloads/develop/springCommuProject/file/video/

